-- MIGRACIÓN COMPLEMENTARIA PARA USER_ACTIVITIES
ALTER TABLE public.user_activities 
ADD COLUMN IF NOT EXISTS visibility TEXT DEFAULT 'PUBLIC' 
CHECK (visibility IN ('PUBLIC', 'FOLLOWERS', 'PRIVATE'));
